# Generated by Django 3.0.5 on 2020-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200426_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='id',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='cookie',
            old_name='user_id',
            new_name='user_ip',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='user_id',
            new_name='user_ip',
        ),
        migrations.AddField(
            model_name='cookie',
            name='host',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='host',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credential',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
