# Generated by Django 3.0.5 on 2020-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20200428_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='cookie_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie',
            field=models.CharField(max_length=1000),
        ),
    ]
