# Generated by Django 3.0.5 on 2020-04-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20200429_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='cookie_name',
        ),
        migrations.RemoveField(
            model_name='cookie',
            name='host',
        ),
        migrations.RemoveField(
            model_name='cookie',
            name='id',
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie',
            field=models.CharField(max_length=2048, primary_key=True, serialize=False),
        ),
    ]
